---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
<<<<<<< HEAD
  - type: directory
    path: pages/posts
    label: Posts
    create: all
    match: "**/*"
    new_doc_ext: md
upload_dir: public
public_path: "/public"
front_matter_path: ""
=======
- type: directory
  path: posts
  label: Posts
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
>>>>>>> e4e1f2945e1c907a3f0944d40fdd866abca9d17a
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
